FROM golang:alpine

RUN apk add --no-cache --update libpng-dev libjpeg-turbo-dev giflib-dev tiff-dev autoconf automake make g++ wget git

WORKDIR /

RUN wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.5.0.tar.gz && \
	echo "7d6fab70cf844bf6769077bd5d7a74893f8ffd4dfb42861745750c63c2a5c92c  libwebp-1.5.0.tar.gz" | sha256sum -c - && \
	tar -xvzf libwebp-1.5.0.tar.gz && \
	mv libwebp-1.5.0 libwebp && \
	rm libwebp-1.5.0.tar.gz && \
	cd /libwebp && \
	./configure && \
	make && \
	make install && \
	cd / && rm -rf libwebp

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go test -v ./...
